website/leads/routes.py
from flask import (Blueprint, render_template, url_for, flash, redirect,
                    request, abort)
from datetime import datetime, date, timedelta
from website import db
from website.models import User, Lead, Status, Origin, History, Meeting
from website.leads.forms import (CreateLeadForm, UpdateLeadForm,
        FilterLeadForm)
from flask_login import current_user, login_required
from sqlalchemy import or_, and_, func

# Declares blueprint
leads = Blueprint('leads', __name__)


# Create a new lead
@leads.route("/lead/create", methods=['GET', 'POST'])
@login_required
def create_lead():
    # initalizes the form
    form = CreateLeadForm()
    
    if request.method == 'GET':
        pass

    elif request.method == 'POST':
        if form.validate_on_submit():

            creation_time = datetime.now()

            lead = Lead(name=form.name.data,
                phone=form.phone.data,
                email=form.email.data,
                description=form.description.data,
                registered=creation_time,
                status_id=form.status.data,
                origin_id=form.origin.data)

            db.session.add(lead)
            db.session.commit()

            history = History(action="Lead criado",
                registered=creation_time,
                user_id=current_user.id,
                lead_id=lead.id)

            db.session.add(history)
            db.session.commit()

            flash('Sua lead foi criada!', 'success')
            return redirect(url_for('leads.list_lead'))
        else:
            flash('Sua lead não foi criada! Verifique seus inputs', 'danger')
    return render_template('create_update_lead.html', title='Criar Lead', form=form, legend='Criar')


# Show a list of existing leads
@leads.route("/lead/list")
@leads.route("/lead/list/<int:status_id>/<int:origin_id>/<date>/<lead_name>/<email>/<description>/<int:page>")
@login_required
def list_lead(page=1, status_id=0, origin_id=0, date="-", phone="-", lead_name="-", email="-", description="-"):
    # builds the search query
    query = or_(Lead.registered >= datetime.now() - timedelta(days=90))

    if status_id != 0:
        query = and_(query, Lead.status_id == status_id)
    
    if origin_id != 0:
        query = and_(query, Lead.origin_id == origin_id)

    if date != "-":
        query = and_(query, func.date(Lead.registered) == date)

    if lead_name != "-":
        query = and_(query, Lead.name.like("%" + lead_name + "%"))
        
    if email != "-":
        query = and_(query, Lead.email.like('%' + email + '%'))

    if description != "-":
        query = and_(query, Lead.description.like('%' + description + '%'))    
    
    leads = Lead.query.filter(query) \
            .order_by(Lead.registered.desc()) \
            .paginate(page=page, per_page=5)
            
    return render_template('list_lead.html', title='Lista de Leads', 
        leads=leads,
        status_id=status_id, origin_id=origin_id, date=date,
        lead_name=lead_name, email=email, description=description)

# Filter a list of existing leads
@leads.route("/lead/filter", methods=['GET', 'POST'])
@login_required
def filter_lead():
    # initalizes the form
    form = FilterLeadForm()

    if form.validate_on_submit():

        lead_name = form.name.data
        phone = form.phone.data
        email = form.email.data
        description = form.description.data
        date = form.date.data
        
        status_id = form.status.data
        origin_id = form.origin.data

        if date == None:
            date = "-"
        if not lead_name:
            lead_name = "-"
        if not phone:
            phone = "-"
        if not email:
            email = "-"
        if not description:
            description = "-"


        return redirect(url_for('leads.list_lead', status_id=status_id, origin_id=origin_id,
                date=date, lead_name=lead_name, phone=phone, email=email, description=description, page=1))

    return render_template('create_update_lead.html', title='Filtrar Lead', form=form)

# Show details of a single lead
@leads.route("/lead/<int:lead_id>/details")
@login_required
def details_lead(lead_id):
    lead = Lead.query.get_or_404(lead_id)
    history = History.query.filter_by(lead_id=lead_id).all()
    operation = Meeting.query.filter(Meeting.lead_id==lead.id, Meeting.start_time >= date.today() + timedelta(days=1)).first()
    if operation == None:
        operation = "schedule"
    else:
        operation = "update"

    return render_template('details_lead.html', title='Detalhe Lead', operation=operation, lead=lead, history=history)

# Update a single lead
@leads.route("/lead/<int:lead_id>/update", methods=['GET', 'POST'])
@login_required
def update_lead(lead_id):
    lead = Lead.query.get_or_404(lead_id)
    
    # initalizes the form
    form = UpdateLeadForm()
    status_list = [(1, "Lead"), (2, "Contato"),
                        (3, "Entrevista"), (4, "Matrícula")]
    status_list.remove((lead.status.id, lead.status.name))
    status_list.insert(0, (lead.status.id, lead.status.name))
    form.status.choices = status_list
    origin_list = [(1, "Site"), (2, "Telefone"), (3, "Rede Social"),
                        (4, "Presencial"), (5, "Indicação")]
    origin_list.remove((lead.origin.id, lead.origin.name))
    origin_list.insert(0, (lead.origin.id, lead.origin.name))
    form.origin.choices = origin_list

    # update lead in database
    if form.validate_on_submit():
        action = "Alteração de "

        if (lead.name != form.name.data or lead.phone != form.phone.data
            or lead.email != form.email.data or lead.description != form.description.data):
            lead.name = form.name.data
            lead.phone = form.phone.data
            lead.email = form.email.data
            lead.description = form.description.data
            action = action + "Dados / "

        if lead.status.id != int(form.status.data):
            action = action + "Status para " + str(dict(status_list).get(int(form.status.data))) + " / "
            lead.status_id = form.status.data
        
        if lead.origin.id != int(form.origin.data):
            action = action + "Origem para " + str(dict(origin_list).get(int(form.origin.data))) + "  "
            lead.origin_id = form.origin.data

        # create new history row
        history = History(action=action[:-2].strip(),
                registered=datetime.now(),
                user_id=current_user.id,
                lead_id=lead.id)

        db.session.add(history)
        db.session.commit()
        flash('Esse Lead foi alterado com sucesso!', 'success')

        return redirect(url_for('leads.details_lead', lead_id=lead.id))

    # populate form
    elif request.method == 'GET':

        form.name.data = lead.name
        form.phone.data = lead.phone
        form.email.data = lead.email
        form.description.data = lead.description

    return render_template('create_update_lead.html', title='Alterar Lead', form=form, legend='Alterar', lead=lead)


# Delete a single lead
@leads.route("/lead/<int:lead_id>/delete", methods=['POST'])
@login_required
def delete_lead(lead_id):
    lead = Lead.query.get_or_404(lead_id)
    # bulk delete
    History.query.filter_by(lead_id=lead_id).delete()
    Meeting.query.filter_by(lead_id=lead_id).delete()

    db.session.delete(lead)
    db.session.commit()
    
    flash('Esse Lead foi deletado com sucesso!', 'success')
    return redirect(url_for('leads.list_lead'))

website/main/routes.py
from flask import Blueprint, render_template

# Declares blueprint
main = Blueprint('main', __name__)


# Show index page
@main.route("/")
@main.route("/index")
def index():
    return render_template('index.html', title='Home')


# Imports for inserting data
from flask import flash, redirect, url_for, request, abort
from flask_login import current_user
from datetime import datetime, date, time, timedelta
from lorem_text import lorem
import random
from random import randint
from website import db, bcrypt
from website.models import User, Lead, History, Availability, Meeting
from website.main.utils import fetch_models, get_rand_datetime
from website.meetings.utils import get_next_working_days
from website.leads.forms import CreateLeadForm

# Show contact page
@main.route("/contact", methods=['GET', 'POST'])
def contact():
    if current_user.is_authenticated:
        flash('Somente usuários não logados!', 'danger')
        abort(403) # 403 = forbidden access
    
    # initalizes the form
    form = CreateLeadForm(status=1)
    
    if request.method == 'GET':
        pass

    elif request.method == 'POST':
        if form.validate_on_submit():

            creation_time = datetime.now()

            lead = Lead(name=form.name.data,
                phone=form.phone.data,
                email=form.email.data,
                description=form.description.data,
                registered=creation_time,
                status_id=form.status.data,
                origin_id=form.origin.data)

            db.session.add(lead)
            db.session.commit()

            history = History(action="Lead criado",
                registered=creation_time,
                user_id=None,
                lead_id=lead.id)

            db.session.add(history)
            db.session.commit()

            flash('Entraremos em contato assim que possível!', 'success')
            return redirect(url_for('main.contact'))
        else:
            flash('Por favor, verifique seus inputs', 'danger')
    
    return render_template('contact.html', title='Contato', form=form, legend='Create')

# Populate the database for the first time with necessary and dummy data
@main.route("/insertdata")
def insertdata():

    (lead_statuses, lead_origins, roles) = fetch_models()

    # create four lead statuses
    db.session.add_all(lead_statuses)
    db.session.commit()

    # create five lead origins
    db.session.add_all(lead_origins)
    db.session.commit()  

    # create two roles
    db.session.add_all(roles)
    db.session.commit()

    # create 10 standard users
    hashed_password = bcrypt.generate_password_hash(
                                    "1234").decode('utf-8')

    users = [
        User(name='Teste da Silva',
                email='teste@teste.com',
                password=hashed_password,
                gender_id=2),
        User(name='Agenore Bruno',
                email='agenorebruno@teste.com',
                password=hashed_password,
                gender_id=1),
        User(name='Amalio Davide',
                email='amaliodavide@teste.com',
                password=hashed_password,
                gender_id=1),
        User(name='Sandra Romani',
                email='sandraromani@teste.com',
                password=hashed_password,
                gender_id=3),
        User(name='Maria Pia Udinese',
                email='mariapiaudinese@teste.com',
                password=hashed_password,
                gender_id=2),
        User(name='Ornella Lettiere',
                email='ornellalettiere@teste.com',
                password=hashed_password,
                gender_id=2),
        User(name='Bernardo Genovesi',
                email='bernardogenovesi@teste.com',
                password=hashed_password,
                gender_id=1),
        User(name='Matteo Cattaneo',
                email='matteocattaneo@teste.com',
                password=hashed_password,
                gender_id=1),
        User(name='Antonio Greece',
                email='antoniogreece@teste.com',
                password=hashed_password,
                gender_id=3),
        User(name='Raffaele Lombardi',
                email='raffaelelombardi@teste.com',
                password=hashed_password,
                gender_id=1)
    ]
    db.session.add_all(users)
    db.session.commit()

    # create 1 administrator user
    administrator = User(name='Administrador',
                email='admin@teste.com',
                password=hashed_password,
                gender_id=1,
                role_id=1)
    
    db.session.add(administrator)
    db.session.commit()
    
    # create 20 standard leads
    start_date = datetime(2024, 5, 20)
    end_date = datetime(2024, 6, 21)
    registered_list = [get_rand_datetime(start_date, end_date)
                        for i in range(20)]
    word_number = 10

    leads = [
        Lead(name='Lorena Gabrielly',
                phone='5573982094195',
                email='lorena-peixoto74@brasildakar.com.br',
                description=lorem.words(word_number),
                registered=registered_list[0],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Diego Isaac Daniel',
                phone='5581996439093',
                email='diego_galvao@emayl.com',
                description=lorem.words(word_number),
                registered=registered_list[1],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Benjamin Thiago Murilo',
                phone='5583983656956',
                email='benjamin_melo@acramisper.com',
                description=lorem.words(word_number),
                registered=registered_list[2],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Manoel Raul Cardoso',
                phone='5591998368434',
                email='manoel-cardoso85@callan.com.br',
                description=lorem.words(word_number),
                registered=registered_list[3],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Helena Jéssica Bernardes',
                phone='5561982403024',
                email='helena_jessica_bernardes@l3ambiental.com.br',
                description=lorem.words(word_number),
                registered=registered_list[4],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='João Marcos Vinicius Enrico',
                phone='5584995238764',
                email='joao_marcos_fernandes@gerj.com.br',
                description=lorem.words(word_number),
                registered=registered_list[5],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Joaquim Cauê das Neves',
                phone='5567997224686',
                email='joaquim.caue.dasneves@protenisbarra.com.br',
                description=lorem.words(word_number),
                registered=registered_list[6],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Olivia Eloá Vieira',
                phone='5583984544170',
                email='oliviaeloavieira@uolinc.com',
                description=lorem.words(word_number),
                registered=registered_list[7],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Bruna Jennifer Carolina Barros',
                phone='5577998444191',
                email='bruna_jennifer_barros@jci.com',
                description=lorem.words(word_number),
                registered=registered_list[8],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Vinicius Gael da Silva',
                phone='5598999683795',
                email='vinicius.gael.dasilva@piemme.com.br',
                description=lorem.words(word_number),
                registered=registered_list[9],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Noah Tomás Novaes',
                phone='5511991185655',
                email='noah_tomas_novaes@sefaz.am.gov.br',
                description=lorem.words(word_number),
                registered=registered_list[10],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Camila Olivia Silvana',
                phone='5566983755255',
                email='camila_olivia_oliveira@alesalvatori.com',
                description=lorem.words(word_number),
                registered=registered_list[11],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Cecília Evelyn Joana',
                phone='5584983374432',
                email='cecilia_freitas@arcante.com.br',
                description=lorem.words(word_number),
                registered=registered_list[12],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Marcela Marina Campos',
                phone='5521995958710',
                email='marcela_marina_campos@asconnet.com.br',
                description=lorem.words(word_number),
                registered=registered_list[13],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Enrico Elias Mendes',
                phone='5551987508226',
                email='enrico.elias.mendes@gmail.com.br',
                description=lorem.words(word_number),
                registered=registered_list[14],
                status_id=randint(1,4),
                origin_id=randint(1,5)),
        Lead(name='Nair Alícia Drumond',
                phone='5588998856713',
                email='nair-drumond71@almaquinas.com.br',
                description=lorem.words(word_number),
                registered=registered_list[15],

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  {% if title %}
    <title>ERP escolar - {{ title }}</title>
  {% else %}
    <title>ERP escolar</title>
  {% endif %}
  
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/erp-escolar-logo.ico') }}" rel="icon">
  <link href="{{ url_for('static', filename='img/erp-escolar-logo.ico') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Muli:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='vendor/animate.css/animate.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet" type="text/css">

  <!-- Template Main CSS File -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

  <!-- =======================================================
  * Template Name: Flattern - v4.7.0
  * Template URL: https://bootstrapmade.com/flattern-multipurpose-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <h1 class="text-light"><a href="{{ url_for('main.index') }}">ERP & CRM escolar</a></h1>
      </div>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a {% if title == "Home" %}class="active"{% endif %} href="{{ url_for('main.index') }}">Home</a></li>
          {% if current_user.is_authenticated %}
          <li class="dropdown"><a href="#"><span>Leads</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{{ url_for('leads.create_lead') }}">Criar Lead</a></li>
              <li><a href="{{ url_for('leads.list_lead') }}">Lista de Leads</a></li>
              <li><a href="{{ url_for('leads.filter_lead') }}">Filtrar Leads</a></li>
            </ul>
          </li>
          <li class="dropdown"><a href="#"><span>Calendário</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{{ url_for('meetings.list_meeting') }}">Agenda</a></li>
              <li><a href="{{ url_for('users.setup_availability') }}">Configurar Disponibilidade</a></li>
            </ul>
          </li>
          <li class="dropdown"><a href="#"><span>Gestão</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{{ url_for('users.account') }}">Minha Conta</a></li>
              {% if current_user.role.name == "Administrador" %}
              <li><a href="{{ url_for('users.register') }}">Criar Novo Usuário</a></li>
              {% endif %}
              <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li><a {% if title == "Contato" %}class="active"{% endif %} href="{{ url_for('main.contact') }}">Contato</a></li>
          <li><a {% if title == "Login" %}class="active"{% endif %} href="{{ url_for('users.login') }}">Login</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    {% if title != 'Home' %}
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>{{ title }}</h2>
          <ol>
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li>{{ title }}</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->
    {% endif %}

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% block content %}
  {% endblock content %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>ERP & CRM Escolar</h3>
            <p>
              Av. Prof. Luciano Gualberto, 380 <br>
              São Paulo, SP 05508-010<br>
              Brasil <br><br>
              <strong>Telefone:</strong> +55 11 99999 9999<br>
              <strong>Email:</strong> contact@erpescolar.com.br<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Links úteis</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>ERP escolar</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flattern-multipurpose-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/waypoints/noframework.waypoints.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  {% if legend == "Marcar" %}
  <script src="{{ url_for('static', filename='js/meeting-select.js') }}"></script>
  {% endif %}

</body>

</html>

website/templates/details_lead.html
{% extends 'base.html' %}
{% block content %}

<!-- ======= Blog Single Section ======= -->
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <article class="entry entry-single">
        <h2 class="entry-title">
          {{ lead.name }}
        </h2>

        <div class="entry-meta">
          <ul>
            <li class="d-flex align-items-center">
              <i class="bi bi-mailbox"></i>
              <a href="mailto:{{ lead.email }}">
                {{ lead.email }}
              </a>
            </li>
            <li class="d-flex align-items-center">
              <i class="bi bi-whatsapp"></i>
              <a href="https://wa.me/+{{ lead.phone }}?text=Olá,%20bom%20dia!">
                +{{ lead.phone[:2] }} ({{ lead.phone[2:4] }}) {{ lead.phone[4:9] }}-{{ lead.phone[9:] }} 
              </a>
            </li>
            <li class="d-flex align-items-center">
              <i class="bi bi-calendar-date"></i>
              {{ lead.registered.strftime("%d/%m/%Y") }}
            </li>
            <li class="d-flex align-items-center">
              <img src="{{ url_for('static', filename='img/lead-statuses/' +
                          lead.status.name) + '.png' }}" class="img-fluid" style="max-height: 1.5em;" alt="">
              &nbsp;
              {{ lead.status.name }}
            </li>
            <li class="d-flex align-items-center">
              <i class="bi bi-people"></i>
              {{ lead.origin.name }}
          </ul>
        </div>
        <div class="entry-content">
          <div class="row">
            <p>
              {{ lead.description }}
            </p>
          </div>
          <div class="row">
            <div class="col-md-12">
              
            <table class="table table-hover table-sm caption-top">
              <caption>Histórico de contatos</caption>
              <thead>
                <tr>
                  <th scope="col">Ação</th>
                  <th scope="col">Usuário</th>
                  <th scope="col">Horário</th>
                </tr>
              </thead>
              <tbody>
                {% for interaction in history %}
                <tr>
                  <td scope="row">
                    {{ interaction.action }}
                  </td>
                  <td scope="row">
                    {% if interaction.user != None %}
                      {{ interaction.user.name }}
                    {% else %}
                      {{ interaction.lead.name }}
                    {% endif %}
                  </td>
                  <td scope="row">
                    {{ interaction.registered }}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            </div>
          </div>          
        </div>
        <div class="entry-footer">
          <i class="bi bi-arrow-return-right"></i>
          <ul class="cats">
            <li><a href="{{ url_for('leads.list_lead') }}">Pesquise por outro Lead</a></li>
          </ul>
          <i class="bi bi-person-workspace"></i>
          <ul class="cats">
            <li><a href="{{ url_for('meetings.schedule_update_meeting', operation=operation, user_id=current_user.id, lead_id=lead.id) }}">{% if operation == "schedule" %}Marcar{% elif operation == "update" %}Remarcar{% endif %} Reunião</a></li>
          </ul>
          <i class="bi bi-arrow-repeat"></i>
          <ul class="cats">
            <li><a href="{{ url_for('leads.update_lead', lead_id=lead.id) }}">Alterar Lead</a></li>
          </ul>
          <i class="bi bi-trash"></i>
          <ul class="cats">
            <li><a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal">Deletar Lead</a></li>
          </ul>          
        </div>

      </article><!-- End blog entry -->
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Deletar Lead</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Você tem certeza que quer deletar esse Lead?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <form action="{{ url_for('leads.delete_lead', lead_id=lead.id)}}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

website/templates/list_meeting.html
{% extends 'base.html' %}
{% block content %}

<section id="testimonials" class="testimonials">
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col">
        <h4>Veja suas próximas reuniões:</h4>
      </div>
    </div>
    <table class="table table-hover table-sm">
      <tbody>
      {% set date_check = "" %}
      {% for meeting in meetings %}
        {% if headings[loop.index0] %}
        <tr class="table-light">
          <td colspan="10">{{ meeting.start_time.strftime("%A, %d de %B de %Y") | capitalize }}</td>
        </tr>
        {% endif %}
        <tr>
          <td style="width:10%">{{ meeting.start_time.strftime("%H:%M") }}</td>
          <td><a href="{{ url_for('meetings.schedule_update_meeting', operation='update', user_id=current_user.id, lead_id=meeting.lead.id) }}">{{ meeting.lead.name }}</a></td>
          {% if current_user.role.name == "Administrador" %}
            <td>{{ meeting.user.name }}</td>
          {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <div class="row mt-2">
        <p>Você pode também <a href="{{ url_for('leads.list_lead') }}">Marcar uma nova reunião</a>!</p>
    </div>
  </div>
</section>

{% endblock content %}